/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
	
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testAppHasAGreetingPatrik() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreetingPatrik());
    }

    @Test public void testAppHasAStringGreeting() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreeting(), "Hello world!");
    }

    @Test public void testAppHasAStringGreetingPatrik() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getGreetingPatrik(), "Hello world, Patrik!");
    }
		
}
