/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
	
    public String getGreeting() {
        return "Hello world!";
    }

    public String getGreetingPatrik() {
        return "Hello world, Patrik!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
