/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
	
    public String getGreeting() {
        return "Hello world!";
    }

    public String getGreetingPatrik() {
        return "Hello world, Patrik!";
    }
}
